import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>NextJS Start</h1>
    </div>
  )
}

export default Home
