import { Button, Input, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Text data-testid="home-title" fontSize="6xl">
        NextJS Typescript Starter
      </Text>
      <Button
        onClick={(): void => {
          alert("pong");
        }}
      >
        Ping
      </Button>
      <Input />
    </div>
  );
};

export default Home;
